spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/instaclone
    username: sa
    password:

  sql:
    init:
      mode: always
      platform: h2
      #schema-locations: classpath:db/h2/schema.sql
      data-locations: classpath:db/h2/data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true


logging.level:
  org.hibernate.SQL: debug